application: go-read
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static

- url: /login/google
  login: required
  script: _go_app

- url: /user/.*
  login: required
  script: _go_app

- url: /.*
  script: _go_app
